"""Builds src/geometry/goldbearSilhouette.js from tools/reference/goldbears.png.

Segments both bears (saturated vs the neutral checkerboard; the olive floor
shadow excluded by hue), normalises them to one height on their mirror axes,
averages them (same mould), mirrors, smooths, and stores the signed distance
field in world units (bear height = 2.0, centred at the origin).
"""
import base64, json, os
import numpy as np, cv2

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'reference', 'goldbears.png')
OUT = os.path.join(HERE, '..', 'src', 'geometry', 'goldbearSilhouette.js')
BEAR_HEIGHT = 2.0
NORM_H = 1200          # working resolution, px per bear height
GRID_CELL = 0.0125     # stored SDF cell, world units
PAD = 0.12             # world-unit margin around the silhouette

bgr = cv2.imread(SRC)
H, W = bgr.shape[:2]
hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
hue = hsv[..., 0].astype(int) * 2
sat = hsv[..., 1].astype(float) / 255
yy, _ = np.mgrid[0:H, 0:W]
orange = (hue < 36) | (hue > 330)
m = ((sat > 0.16) & ((yy < 655) | orange)).astype(np.uint8) * 255
m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (9, 9)))
m = cv2.morphologyEx(m, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5)))
n, lab, stats, _ = cv2.connectedComponentsWithStats(m)
bears = sorted([i for i in range(1, n) if stats[i][4] > 20000], key=lambda i: stats[i][0])
assert len(bears) == 2, stats

def mirror_axis(mask, x, w):
    best = None
    for c2 in range(2 * x + w - 16, 2 * x + w + 17):
        ref = np.zeros_like(mask)
        for col in range(x, x + w):
            mc = c2 - col
            if 0 <= mc < mask.shape[1]:
                ref[:, col] = mask[:, mc]
        score = np.sum((mask > 0) != (ref > 0))
        if best is None or score < best[0]:
            best = (score, c2 / 2)
    return best[1]

norm = []
aspect = []
for i in bears:
    b = (lab == i).astype(np.uint8) * 255
    ff = b.copy()
    cv2.floodFill(ff, np.zeros((H + 2, W + 2), np.uint8), (0, 0), 255)
    b = b | cv2.bitwise_not(ff)
    x, y, w, h = cv2.boundingRect(b)
    ax = mirror_axis(b, x, w)
    s = NORM_H / h
    half = int(np.ceil(max(ax - x, x + w - ax) * s)) + 4
    canvas_w = 2 * half
    M = np.float32([[s, 0, half - ax * s], [0, s, -y * s]])
    nb = cv2.warpAffine(b.astype(np.float32) / 255, M, (canvas_w, NORM_H), flags=cv2.INTER_LINEAR)
    nb = 0.5 * (nb + nb[:, ::-1])  # mirror
    norm.append(nb)
    aspect.append(h / w)
cw = max(a.shape[1] for a in norm)
acc = np.zeros((NORM_H, cw), np.float32)
for a in norm:
    off = (cw - a.shape[1]) // 2
    acc[:, off:off + a.shape[1]] += a / len(norm)
acc = cv2.GaussianBlur(acc, (0, 0), 2.5)
mask = (acc > 0.5).astype(np.uint8)

# padded canvas, then exact signed distance (px) → world units
px_per_unit = NORM_H / BEAR_HEIGHT
pad_px = int(PAD * px_per_unit)
mask = cv2.copyMakeBorder(mask, pad_px, pad_px, pad_px, pad_px, cv2.BORDER_CONSTANT, value=0)
inside = cv2.distanceTransform(mask, cv2.DIST_L2, cv2.DIST_MASK_PRECISE)
outside = cv2.distanceTransform(1 - mask, cv2.DIST_L2, cv2.DIST_MASK_PRECISE)
sdf_px = outside - inside
hh, ww = sdf_px.shape
cols = int(round(ww / px_per_unit / GRID_CELL))
rows = int(round(hh / px_per_unit / GRID_CELL))
sdf = cv2.resize(sdf_px, (cols, rows), interpolation=cv2.INTER_AREA) / px_per_unit
sdf = np.flipud(sdf).astype(np.float32)  # row 0 = bottom (world y up)

width_units = ww / px_per_unit
height_units = hh / px_per_unit
meta = {
    'cols': cols, 'rows': rows,
    'x0': -width_units / 2, 'y0': -height_units / 2,
    'dx': width_units / cols, 'dy': height_units / rows,
}
data = base64.b64encode(sdf.tobytes()).decode()
widths = []
for v in [0.05, 0.1, 0.2, 0.3, 0.35, 0.45, 0.55, 0.62, 0.7, 0.8, 0.9, 0.97]:
    r = pad_px + int(v * NORM_H)
    xs = np.where(mask[r] > 0)[0]
    widths.append((v, round((xs.max() - xs.min()) / NORM_H, 3)))
with open(OUT, 'w') as f:
    f.write('// Generated by tools/build-silhouette.py from tools/reference/goldbears.png — do not edit.\n')
    f.write('// Signed distance (world units, negative inside) of the Goldbear outline;\n')
    f.write('// row 0 is the bottom, bear height 2.0 centred on the origin.\n')
    f.write(f'export const SILHOUETTE = {json.dumps(meta)}\n')
    f.write(f'export const SILHOUETTE_DATA = "{data}"\n')
print('aspect h/w per bear', [round(a, 3) for a in aspect])
print('grid', cols, 'x', rows, 'cell', round(meta['dx'], 4), 'bytes', len(data))
print('width/height at v:', widths)
cv2.imwrite('/tmp/ref-sil-final.png', (mask * 255))
